### PR TITLE
Rename the molecule validation regex

### LINKED ISSUE #221: Accept single quotes in the molecule validation regex

### PR DESCRIPTION
**Pull request by FrancoisPog**
closes #221 
At first I thought there was a problem but finally not, but the name of the constant misled me, so I renamed it.

### CODE REVIEW

**Review by nathanaelhoun — CHANGES_REQUESTED** [review]
I don't understand your changes, I think you are trying to scuttle the project!

**Review by nathanaelhoun — APPROVED** [review]
(just laughing)

**Comment by FrancoisPog** [comment]
the point is we say single quotes are allowed in the names of molecules, but if we just look at the VALID_DCI_REGEX we don't see the single quote and we can't figure it out, the REGEX is for normalized names and it is more clear to clarify it. 😉

**Review by valentinperignon — APPROVED** [review]
LGTM
But please, in the future split the work in several PRs when there are so many changes

**Comment by nathanaelhoun** [comment]
> the point is we say single quotes are allowed in the names of molecules, but if we just look at the VALID_DCI_REGEX we don't see the single quote and we can't figure it out, the REGEX is for normalized names and it is more clear to clarify it. wink

So if I understand correctly, the REGEX is for normalized names (not molecules names) and the normalized names can't contains quotes, whereas molecules names can?

I think you are trying to add an extra overhead to all the contributors here and it's not a good idea.

**Comment by nathanaelhoun** [comment]
Even your PR name does not correspond to the content of the PR

**Comment by nathanaelhoun** [comment]
Grrrr

**Comment by nathanaelhoun** [comment]
And you merged it? I lock the conversation.

**Pull request merged**
