### PR TITLE
API: Fix challengeable users request

### LINKED ISSUE #252: Fix filter `challengeable` for users requests
Currently the controller uses the `getDuelOf` procedure to filter the challengeable users, but this procedure also returns the finished duels, so we need to check if the duel is finished to filter.
So currently, we must wait for the deletion of the last duel to be able to challenge the user again.

- [x] Fix the filter
- [x] Add unit tests for this case

### PR DESCRIPTION
**Pull request by nathanaelhoun**
## Changes

- [x] Fix challengeable users API endpoint not returning users with finished duels, by making an entirely different database request
- [x] Added a unit test

Closes #252.

### CODE REVIEW

**Review by valentinperignon — APPROVED** [review]
LGTM

**Review by FrancoisPog — COMMENTED** [review]
did you only add a before in the tests ? :thinking:

**Comment by nathanaelhoun** [comment]
@FrancoisPog There was already a test case requesting the challengeable users, which expect 2 users to not be challenged and 2 to be challenged. So I added one of the "not challenged" in a finished challenge.

(this test case fails on `main` but succeed here, so the bug is correctly identified :wink:)

**Review by FrancoisPog — APPROVED** [review]
Oh ok I forgot that we already had tests for this ! :grin:

**Pull request merged**
